// <auto-generated />
namespace foy5form_but.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Kurulum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kurulum));
        
        string IMigrationMetadata.Id
        {
            get { return "202507011227482_Kurulum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
